# Generated by Django 5.0.7 on 2024-08-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_post',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news_post',
            name='author',
            field=models.CharField(default='Ilya', max_length=50, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
